# Aetherelic MangoHud config

legacy_layout=false
horizontal
hud_no_margin
background_alpha=0.35
round_corners=8

font_size=22
font_scale=1.0

fps
frametime
gpu_stats
gpu_temp
gpu_load_change
cpu_stats
cpu_temp
ram
vram
gamemode
engine_version
vulkan_driver

fps_limit_method=late

toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
reload_cfg=Shift_L+F4
