font_family JetBrainsMono Nerd Font
font_size 11

background #080d10
foreground #9db6ad
background_opacity 0.42
dynamic_background_opacity yes

cursor #9db6ad
cursor_shape block
cursor_blink_interval 0

window_padding_width 10
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 1
