font_family JetBrainsMono Nerd Font
font_size 15

background #080d10
foreground #dce0da
background_opacity 0.78
dynamic_background_opacity yes

cursor #9db6ad
cursor_shape block
cursor_blink_interval 0

window_padding_width 22
hide_window_decorations yes
confirm_os_window_close 0
enable_audio_bell no
scrollback_lines 1
