#!/usr/bin/env python3
from pathlib import Path
import json
import os

home = Path.home()
colors_path = home / ".config/quickshell/Colors/colors.json"
wall_path = home / ".config/hypr/current_wallpaper"
out = home / ".config/hypr/hyprlock.conf"

def hex_to_rgba(hex_color, alpha=1.0):
    h = str(hex_color).strip().lstrip("#")
    if len(h) != 6:
        return f"rgba(255, 255, 255, {alpha})"
    r = int(h[0:2], 16)
    g = int(h[2:4], 16)
    b = int(h[4:6], 16)
    return f"rgba({r}, {g}, {b}, {alpha})"

colors = {}
try:
    colors = json.loads(colors_path.read_text())
except Exception:
    pass

bg = colors.get("background", "#0b0b10")
fg = colors.get("on_surface", "#ffffff")
muted = colors.get("on_surface_variant", "#b8b8c0")
accent = colors.get("primary", "#cba6f7")
surface = colors.get("surface_container", "#15151d")

wall = str(wall_path)
user = os.environ.get("USER", "aetherelic")

conf = f"""# =========================================================
# Aetherelic adaptive hyprlock
# Auto-generated by generate-hyprlock-theme.py
# =========================================================

general {{
    hide_cursor = true
    ignore_empty_input = true
    disable_loading_bar = true
}}

background {{
    monitor =
    path = {wall}
    color = {hex_to_rgba(bg, 1.0)}
    blur_size = 8
    blur_passes = 3
    noise = 0.0117
    contrast = 1.0500
    brightness = 0.7200
    vibrancy = 0.1800
    vibrancy_darkness = 0.2000
}}

label {{
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = {hex_to_rgba(fg, 1.0)}
    font_size = 96
    font_family = JetBrainsMono Nerd Font
    position = 0, 190
    halign = center
    valign = center
    shadow_passes = 3
    shadow_size = 8
    shadow_color = rgba(0, 0, 0, 0.45)
}}

label {{
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = {hex_to_rgba(muted, 0.95)}
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 105
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.35)
}}

label {{
    monitor =
    text =   {user}
    color = {hex_to_rgba(accent, 1.0)}
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, -30
    halign = center
    valign = center
    shadow_passes = 2
    shadow_size = 5
    shadow_color = rgba(0, 0, 0, 0.35)
}}

input-field {{
    monitor =
    size = 420, 58
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    fade_on_empty = false

    outer_color = {hex_to_rgba(accent, 0.75)}
    inner_color = {hex_to_rgba(surface, 0.42)}
    font_color = {hex_to_rgba(fg, 1.0)}
    placeholder_text = <i>Enter password...</i>
    fail_text = <i>Access denied</i>

    rounding = 18
    check_color = {hex_to_rgba(accent, 0.85)}
    fail_color = rgba(255, 95, 95, 0.85)
    capslock_color = rgba(249, 226, 175, 0.90)

    position = 0, -110
    halign = center
    valign = center

    shadow_passes = 3
    shadow_size = 8
    shadow_color = rgba(0, 0, 0, 0.38)
}}

label {{
    monitor =
    text = Press ESC to return
    color = {hex_to_rgba(muted, 0.75)}
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = 0, -190
    halign = center
    valign = center
}}
"""

out.write_text(conf)
print(f"Wrote {out}")
