wallpaper {
    monitor = DP-2
    path = /home/aetherelic/Pictures/Wallpapers/maindisplay.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = /home/aetherelic/Pictures/Wallpapers/sidedisplay.jpg
    fit_mode = cover
}
